### ISSUE TITLE
[사용자경험 개선 제안]회원가입

### ISSUE THREAD

**Issue by limdongjin** [KKambi/toy-login#1]
1. 관심사 작성과 관련한 설명이 추가되면 좋을것같음.

현재는 회원가입 관심사 항목 작성시에, 
관심사를 추가할려면 콤마(,)로 구분해야 하는것같음.

하지만 콤마로 관심사를 구분한다는 설명이 없기때문에, 
콤마로 구분되는 구조임을 알기 어려움. 

2. 사용자의 엔터를 무시하도록 되어있으면 좋을것같음

회원가입 항목들(input) 작성시에 무심코 엔터를 누르게 되는데 이때 엔터를 누르면 초기화 버튼이 눌리면서 
'모든 내용을 새로 작성하겠습니까?' 라는 메세지가 뜨게됨. 
사용자의 엔터가 무시되도록 설정하면 좋을것같음

**Comment by KKambi** [comment]
와 이거 지금 봤다 왜 지금 봤지
고맙습니다~
